version: '3'
services:
  moodle:
    container_name: moodle
    image: moodle
    restart: always
    build:
      context: ./moodle
    ports:
      - 80:80
    environment:
      - MOODLE_DB=mysql
      - MOODLE_DBPASS=moodle
      - MOODLE_HOST=http://localhost
    volumes:
      - ./data/moodle:/var/moodledata
    links:
      - mysql

  mysql:
    container_name: mysql
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    ports:
      - 3306:3306
    environment:
    - MYSQL_DATABASE=moodle
    - MYSQL_ROOT_PASSWORD=moodle
    volumes:
      - ./data/mysql:/var/lib/mysql
